<div id="modal_politicasdeprivacidad" class="modal modal-fixed-footer">
  <div class="modal-content">
    <i class="material-icons right modal-close">close</i>
    <h3 class="card-title">Políticas de privacidad</h3>
    <p>Los datos que se proporcionen a Botón de Pago S.A. podrán utilizarse para procesar sus pedidos, compras, solicitudes, denuncias, reclamos, para la relación comercial y fines publicitarios. Disposición DNPDP 10/2008: "El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326" y "La DIRECCION NACIONAL DE PROTECCION DE DATOS PERSONALES, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales."</p>
    <p><b>1. Nuestro Compromiso con la Privacidad</b></p>
    <p>Botón de Pago S.A. (en adelante, “Todo Pago”) respeta la privacidad de toda persona que visite nuestro sitio Web y/o realice alguna compra/operación a través de las soluciones disponibles de Todo Pago. Esta Política de Privacidad indica la información que Todo Pago puede recopilar y el uso que puede dar a esa información (en adelante, los “Datos”).</p><br>

    <p><b>Principios</b></p>
    <p>Las bases de datos que trata Todo Pago se encuentran debidamente inscriptas ante la Dirección Nacional de Protección de Datos Personales y no tienen finalidades contrarias a las leyes y/o a la moral pública.</p>
    <p>Los datos personales que se recojan a los efectos de su tratamiento serán ciertos, adecuados, pertinentes y no excesivos en relación al ámbito y finalidad para los que se obtuvieron. La recolección de datos no se efectúa por medios desleales, fraudulentos o en forma contraria a las disposiciones de la Normativa de Protección de los Datos Personales. Los datos objeto de tratamiento no serán utilizados para finalidades distintas o incompatibles con aquellas que motivaron su obtención.</p>
    <p>Los datos que forman parte de las bases de datos que trata Todo Pago deberán ser proporcionados exactos y actualizarse en el caso que ello fuere necesario.</p>
    <p>Los datos total o parcialmente inexactos, o que sean incompletos, podrán ser suprimidos y sustituidos, o en su caso completados por Todo Pago cuando se tenga conocimiento de la inexactitud o carácter incompleto de la información de que se trate, sin perjuicio de los derechos del titular de rectificación, actualización o supresión.</p>
    <p>Los datos serán almacenados de modo que permitan el ejercicio del derecho de acceso de su titular.</p>
    <p>Los datos serán destruidos cuando hayan dejado de ser necesarios o pertinentes a los fines para los cuales hubiesen sido recolectados.</p>
    <p>Los datos personales que trata Todo Pago han sido brindados por sus titulares prestando su consentimiento libre, expreso e informado, salvo en los siguientes casos autorizados por la Normativa de Protección de los Datos Personales:</p>
    <p>a) Cuando los datos se obtengan de fuentes de acceso público irrestricto;</p>
    <p>b) Cuando los datos se recaben para el ejercicio de funciones propias de los poderes del Estado o en virtud de una obligación legal;</p>
    <p>c) Cuando se trate de listados cuyos datos se limiten a nombre, documento nacional de identidad, identificación tributaria o previsional, ocupación, fecha de nacimiento y domicilio;</p>
    <p>d) Cuando deriven de una relación contractual, científica o profesional del titular de los datos, y resulten necesarios para su desarrollo o cumplimiento;</p>
    <p>e) Se trate de las operaciones que realicen las entidades financieras y de las informaciones que reciban de sus clientes conforme las disposiciones del art. 39 de la Ley Nº 21.526.</p>
    <p>Cuando Todo Pago recaba datos personales, informará previamente a sus titulares los siguientes lineamientos:</p>
    <p>a) La finalidad para la que serán tratados y quienes pueden ser sus destinatarios o clase de destinatarios;</p>
    <p>b) La existencia del archivo, registro, banco de datos, electrónico o de cualquier otro tipo, de que se trate y la identidad y domicilio de su responsable;</p>
    <p>c) El carácter obligatorio o facultativo de las respuestas al cuestionario que se le proponga, en especial en cuanto a los datos sensibles, si se recolectaren los mismos;</p>
    <p>d) Las consecuencias de proporcionar datos, de la negativa a hacerlo o de la inexactitud de los mismos;</p>
    <p>e) La posibilidad del titular de los datos de ejercer los derechos de acceso, rectificación y supresión de sus datos. Todo Pago no solicitará a los titulares de datos que proporcionen datos sensibles, salvo por obligación legal. Todo Pago no efectuará cesiones de los datos personales contenidos en las bases de datos, salvo por obligación legal.</p><br>

    <p><b>2. Recopilación y Utilización de sus Datos</b></p>
    <p>Esta Política de Privacidad contempla la recopilación y uso de información personal que se brinda a través de la utilización del sitio de Internet www.todopago.com.ar (en adelante, el “SITIO”), de la Cuenta Todo Pago que forma parte del SITIO y/o de las soluciones de pago disponibles por Todo Pago.</p>
    <p>En caso de que usted nos brinde Datos, le comunicamos que dichos Datos serán objeto de tratamiento automatizado e incorporada a la base de datos de Todo Pago.</p>
    <p>Asimismo le informamos que podemos utilizar esos Datos conforme se indica a continuación salvo indicación en contrario:</p>
    <p>•  podemos guardar y procesar esos Datos para comprender mejor sus necesidades y saber cómo mejorar nuestros productos y servicios;</p>
    <p>• podemos tratar sus Datos para procesar sus pedidos, operaciones/compras, solicitudes, denuncias, reclamos, utilizarla para la relación comercial y fines publicitarios, etc.; o podemos elaborar estadísticas en base a ella;</p>
    <p>• podemos utilizar esa información para comunicarnos con usted, y/o podemos suministrar a terceros información global, pero no individual, sobre los visitantes o usuarios de nuestro sitio.</p><br>

    <p><b>3. Datos</b></p>
    <p>Todo Pago recopila Datos en línea cuando:</p>
    <p>• Usted se registra para hacer uso de alguno de los servicios disponibles del SITIO y/o de la Cuenta Todo Pago y/o de las soluciones de pago disponibles por Todo Pago.</p>
    <p>• Usted utiliza el SITIO y/o la Cuenta Todo Pago y/o las soluciones de pago disponibles por Todo Pago.</p>
    <p>• Usted nos envía preguntas o comentarios o Usted solicita información o materiales.</p>
    <p>• Usted efectúa denuncias o reclamos.</p>
    <p>• Usted reporta algún incidente en Internet.</p>
    <p>• Usted provee de cualquier forma información al SITIO y/o a la Cuenta Todo Pago y/o cuando utiliza las soluciones de pago disponibles por Todo Pago (chats, foros, uploads, etc.)</p>
    <p>El tipo de información recopilada puede incluir nombre, tipo y número de documento, teléfono, dirección de correo electrónico y/o cualquier otra información que permita individualizarlo. En todos los casos que usted brinde Datos, y de acuerdo a la legislación vigente, usted declara que la información brindada es cierta.</p>
    <p>En los casos que usted nos brinde sus Datos, usted acepta y presta su consentimiento libre, expreso e informado para que dichos Datos sean utilizados con las finalidades arriba mencionadas, y autoriza a que los mismos sean tratados, almacenados, recopilados en las bases de datos de propiedad de Todo Pago. Asimismo, usted acepta y presta su consentimiento libre, expreso e informado con los términos de la presente Política de Privacidad.</p><br>

    <p><b>4. Correo Electrónico</b></p>
    <p>Todo Pago podrá enviarle correos electrónicos en relación al contenido de la compra/ operación, del SITIO o sobre su Cuenta Todo Pago y en respuesta a sus preguntas. Todo Pago también le podrá enviar correos electrónicos con información, publicidades u ofertas especiales sobre productos y servicios que le puedan interesar, a menos que usted indique que no desea recibir dichos correos electrónicos. Ud. podrá, en cualquier momento, solicitar el retiro o bloqueo de su nombre de la base de datos a los que se refiere la presente Política de Privacidad, conforme la Ley 25.326, art. 27 inciso 3ro. Todo correo electrónico que reciba de Todo Pago le informará cómo rechazar el envío de futuros correos electrónicos promocionales. Podrá cambiar sus preferencias de correo electrónico en cualquier momento. Vea más adelante la sección "Manteniendo Precisa su Información".</p><br>

    <p><b>5. Compartiendo Sus Datos</b></p>
    <p>Sin perjuicio de ello, Todo Pago podrá compartir todos los datos que hemos recopilado según se describió anteriormente con las empresas afiliadas y/o vinculadas y/o los intermediarios que realizan servicios de comercialización en nuestro nombre o con quienes tengamos acuerdos de comercialización. A este respecto, Ud. autoriza a Todo Pago a compartir los Datos suministrados con las empresas controlantes, afiliadas, subsidiarias, empresas vinculadas y/o los intermediarios relacionados con Todo Pago. Dicha información será revelada, compartida o cedida de acuerdo con la legislación vigente en la República Argentina aplicable a la protección de datos personales. Todo Pago podrá revelar los Datos a terceros sin su consentimiento tal como es requerido por ley o por resolución judicial que así lo autorice, para cooperar con autoridades gubernamentales en investigaciones judiciales y para hacer cumplir o proteger la propiedad intelectual o derechos contractuales de Todo Pago.</p><br>

    <p><b>6. Otra Información – Cookies</b></p>
    <p>Cuando usted ingresa en el SITIO y/o en la Cuenta Todo Pago y/o en las soluciones de pago disponibles por Todo Pago, Todo Pago podrá almacenar alguna información en su computadora bajo la forma de una "Cookie" o archivo similar que puede sernos útil de varias formas. Por ejemplo, las Cookies nos permiten diseñar un sitio Web de forma tal de poder satisfacer en mayor medida sus intereses y preferencias. Con la mayoría de los exploradores para Internet, usted puede borrar las Cookies del disco rígido de su computadora, bloquear todas las Cookies o recibir un mensaje de alerta antes de que se almacene una Cookie. Remitirse a las instrucciones de su explorador o a la pantalla de ayuda para conocer más sobre estas funciones.</p><br>

    <p><b>7. Protegiendo Su Información</b></p>
    <p>Para prevenir acceso no autorizado, mantener la precisión de los datos y asegurar el uso correcto de la información, Todo Pago ha puesto en uso ciertos medios físicos, electrónicos, administrativos y procedimientos de seguridad para resguardar y asegurar la información que recopilamos en línea. Nosotros resguardamos la información de acuerdo a estándares y procedimientos de seguridad establecidos y continuamente evaluamos nueva tecnología para proteger información. Todo Pago garantiza que los procesos internos propios de las bases de datos cumplen con las obligaciones legales de seguridad y confidencialidad impuestas por la Ley de Protección de Datos Personales N° 25.326.</p>
    <p>Sin embargo, Usted reconoce que los medios técnicos existentes que brindan seguridad no son inexpugnables, y que aún cuando se adopten todos los recaudos razonables de seguridad es posible sufrir manipulaciones, destrucción y/o pérdida de información.</p>
    <p>Por otro lado, mientras intentamos proteger sus Datos, Usted también deberá tomar medidas para proteger su información. Le insistimos en que tome toda precaución para proteger su información personal mientras está en Internet. Como mínimo, le aconsejamos que cambie su clave de acceso periódicamente, usando una combinación de letras y números y se asegure de que está utilizando un navegador seguro al estar en Internet.</p><br>

    <p><b>8. Privacidad de Menores</b></p>
    <p>Todo Pago no tiene intenciones de recopilar Datos de menores de edad. Cuando corresponda, Todo Pago le indicará específicamente a los menores que no brinden esa información en nuestro Sitio y/o tomará medidas razonables para obtener el consentimiento de los padres/tutores/representantes a la entrega de esa información.</p>
    <p>Le informamos que en su condición de padre, tutor legal o representante será el responsable de que sus hijos menores o bajo su tutela accedan al SITIO y/o a la Cuenta Todo Pago y/o a las soluciones de pago disponibles por Todo Pago por lo que recomendamos enfáticamente tomar las precauciones oportunas durante la navegación en el SITIO y/o en la Cuenta Todo Pago y/o en las soluciones de pago disponibles por Todo Pago. A este fin, le informamos que algunos navegadores permiten configurarse para que los niños no puedan acceder a páginas determinadas.</p>
    <p>Usted podrá ponerse en contacto con Todo Pago para realizar las sugerencias o advertencias que considere oportunas.</p><br>

    <p><b>9. Publicidad directa</b></p>
    <p>Con el fin de efectuar publicidades, Todo Pago podrá tratar datos personales que sean aptos para establecer perfiles determinados con fines promocionales, comerciales o publicitarios, o permitan establecer hábitos de consumo, cuando éstos figuren en documentos accesibles al público o hayan sido facilitados por los propios titulares u obtenidos con su consentimiento.</p>
    <p>En cumplimiento de lo dispuesto por la Disposición Nº 10/08, Todo Pago incluye en lugar visible en su página web y en los formularios utilizados para la recolección de datos personales, una leyenda que indica: "El titular de los datos personales tiene la facultad de ejercer el derecho de acceso a los mismos en forma gratuita a intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto conforme lo establecido en el artículo 14, inciso 3 de la Ley Nº 25.326. La DIRECCION NACIONAL DE PROTECCION DE DATOS PERSONALES, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales.</p>
    <p>"De conformidad con lo establecido por la Disposición Nº 4/09, en las comunicaciones con fines de publicidad directa, Todo Pago debe incorporar el siguiente aviso: “DERECHOS SOBRE SUS DATOS PERSONALES. Ley Nº 25.326 Art. 27 (Archivos, registros o bancos de datos con fines de publicidad). Inc. 3. El titular podrá en cualquier momento solicitar el retiro o bloqueo de su nombre de los bancos de datos a los que se refiere el presente artículo. Dto. Nº 1558/2001 Art. 27. En toda comunicación con fines de publicidad que se realice por correo, teléfono, correo electrónico, internet u otro medio a distancia a conocer, se deberá indicar, en forma expresa y destacada, la posibilidad del titular del dato de solicitar el retiro o bloqueo, total o parcial, de su nombre de la base de datos. A pedido del interesado, se deberá informar el nombre del responsable o usuario del banco de datos que proveyó la información. Si desea dejar de recibir mensajes vía e-mail con publicidad del Servicio de Notificaciones Todo Pago, ingrese en www.todopago.com.ar identificándose con Usuario y Clave Privada en la Sección Perfil, Preferencias. Botón de Pago S.A Tucumán 1 piso 4. CUIT 30-71460028-8.</p>
    <p>Asimismo, cuando Todo Pago efectúe envíos de comunicaciones de publicidad directa no requeridas o consentidas previamente por el titular del dato personal, advertirá en forma destacada que se trata de una publicidad. En caso de realizarse dicha comunicación a través de un correo electrónico insertará en su encabezado el término único "publicidad".</p><br>

    <p><b>10. Links Externos</b></p>
    <p>Algunos sitios de Internet de Todo Pago pueden contener links hacia y provenientes de otros sitios de Internet. Todo Pago no es responsable por las prácticas de privacidad ni el tratamiento de los datos personales de esos sitios. Todo Pago los alienta a que averigüen las prácticas de privacidad de dichos sitios de Internet antes de su utilización.</p><br>

    <p><b>11. Manteniendo Precisa su Información</b></p>
    <p>Si Usted ha proporcionado Datos a través de los servicios disponibles en el SITIO y/o en la Cuenta Todo Pago y cualquiera de sus Datos cambia, Usted podrá revisar, modificar, eliminar y actualizar sus datos personales en el momento que desee.</p>
    <p>Asimismo, y de conformidad con la legislación vigente, Usted podrá solicitar el ejercicio de su derecho de acceso, rectificación o supresión de sus Datos. De esta manera, usted tiene la opción de visualizar y cambiar su información ingresando al SITIO con Usuario y Clave Privada en la sección Perfil o bien presentar nota escrita al domicilio legal de Botón de Pago S.A., indicando su requerimiento y acreditando fehacientemente su identidad.<br>El derecho de acceso a los datos podrá ser ejercido en forma gratuita por el interesado en la medida que la correspondiente información sea solicitada en intervalos no inferiores a seis meses, salvo que se acredite un interés legítimo al efecto, conforme artículo 14, inciso 3 de la Ley 25.326.<br>Si los datos son incorrectos, desea actualizarlos y/o suprimirlos, puede hacerlo desde el SITIO con Usuario y Clave Privada en la Sección Perfil. La corrección, actualización y/o supresión de la información se realizará a su requerimiento sin costo alguno, conforme artículo 16 de la Ley 25.326. Alternativamente podrá enviar un correo electrónico a la dirección información@todopago.com.ar, con el asunto "Informar", "Rectificar", "Suprimir" y/o "Actualizar" según corresponda, conjuntamente con el objeto de su requerimiento.</p>
    <p>Todo Pago hará todos los esfuerzos razonables para hacer que sus solicitudes sean cumplidas.</p>
    <p>Se hace saber que la DNPDP, Órgano de Control de la Ley Nº 25.326, tiene la atribución de atender las denuncias y reclamos que se interpongan con relación al incumplimiento de las normas sobre protección de datos personales.</p><br>

    <p><b>12. Contactos en Todo Pago y Vigilancia</b></p>
    <p>Si tiene preguntas sobre su privacidad cuando usa el SITIO y/o la Cuenta Todo Pago y/o las soluciones de pago disponibles por Todo Pago por favor contáctenos desde el Formulario disponible en el SITIO </p><br>

    <p><b>13. Cambios a esta Política de Privacidad</b></p>
    <p>Todo Pago se reserva el derecho a modificar esta Política de Privacidad periódicamente. Usted se compromete a revisar regularmente estas Políticas de Privacidad a fin de informarse de cualquier cambio que se pueda haber producida.</p>

  </div>
  <div class="modal-footer right-align">
    <a href="#!" class="modal-action modal-close waves-effect waves-light btn-flat blue-text">Cerrar</a>
  </div>
</div>
